import { InvestmentData } from "@/types";
import { BorrowData } from "@/types/borrowData";

const investments: InvestmentData[] = [
    {
        tokenSymbol: "USDC",
        netAPY: 14.1,
        totalDeposits: 3289.62,
        totalValueUSD: 1.96,
        curator: "Flowverse",
        collateral: ["usdc", "btc", "add"],
        unsecured: 7890.12,
        unsecuredAPY: 16.8,
        credoraRating: "B / AA+",
    },
    {
        tokenSymbol: "USDT",
        netAPY: 12.3,
        totalDeposits: 5432.1,
        totalValueUSD: 3.25,
        curator: "AXA",
        collateral: ["usdc", "btc", "add"],
        unsecured: 6543.21,
        unsecuredAPY: 13.5,
        credoraRating: "B / AA+",
    },
    {
        tokenSymbol: "USDA",
        netAPY: 8.6,
        totalDeposits: 7654.32,
        totalValueUSD: 1.55,
        curator: "Enjin",
        collateral: ["usdc", "ada", "add", "aave"],
        unsecured: 4321.09,
        unsecuredAPY: 17.5,
        credoraRating: "B / AA+",
    },
    {
        tokenSymbol: "USDC",
        netAPY: 4.9,
        totalDeposits: 2987.65,
        totalValueUSD: 5.02,
        curator: "Plygon",
        collateral: ["usdc", "ada", "add", "aave"],
        unsecured: 8765.43,
        unsecuredAPY: 15.9,
        credoraRating: "B / AA+",
    },
    {
        tokenSymbol: "USDT",
        netAPY: 15.3,
        totalDeposits: 4567.89,
        totalValueUSD: 2.89,
        curator: "adder",
        collateral: ["usdc", "algo", "add"],
        unsecured: 8765.43,
        unsecuredAPY: 18.5,
        credoraRating: "B / AA+",
    },
    {
        tokenSymbol: "USDT",
        netAPY: 14.7,
        totalDeposits: 9876.54,
        totalValueUSD: 6.34,
        curator: "Metaverse",
        collateral: ["usdc", "algo", "add"],
        unsecured: 3210.98,
        unsecuredAPY: 14.7,
        credoraRating: "B / AA+",
    },
    {
        tokenSymbol: "USDA",
        netAPY: 13.8,
        totalDeposits: 1234.56,
        totalValueUSD: 0.75,
        curator: "Bitcoin",
        collateral: ["usdc", "0xbtc", "ada"],
        unsecured: 6789.01,
        unsecuredAPY: 15.9,
        credoraRating: "B / AA+",
    },
    {
        tokenSymbol: "DAI",
        netAPY: 12.7,
        totalDeposits: 6789.01,
        totalValueUSD: 3.99,
        curator: "Bitcoin",
        collateral: ["usdc", "btc", "add", "aave"],
        unsecured: 9876.54,
        unsecuredAPY: 12.3,
        credoraRating: "B / AA+",
    },
    {
        tokenSymbol: "Walgo",
        netAPY: 15.3,
        totalDeposits: 3210.98,
        totalValueUSD: 1.87,
        curator: "Bitcoin",
        collateral: ["usdc", "algo", "add"],
        unsecured: 4567.89,
        unsecuredAPY: 7.8,
        credoraRating: "B / AA+",
    },
    {
        tokenSymbol: "Wadd",
        netAPY: 8.9,
        totalDeposits: 8765.43,
        totalValueUSD: 5.67,
        curator: "Bitcoin",
        collateral: ["usdc", "btc", "add", "aave"],
        unsecured: 2987.65,
        unsecuredAPY: 4.6,
        credoraRating: "B / AA+",
    },
    {
        tokenSymbol: "USDA",
        netAPY: 18.4,
        totalDeposits: 4321.09,
        totalValueUSD: 2.45,
        curator: "Bitcoin",
        collateral: ["usdc", "algo", "add"],
        unsecured: 7654.32,
        unsecuredAPY: 8.2,
        credoraRating: "B / AA+",
    },
    {
        tokenSymbol: "USDT",
        netAPY: 12.3,
        totalDeposits: 6543.21,
        totalValueUSD: 3.67,
        curator: "Bitcoin",
        collateral: ["usdc", "btc", "add", "aave"],
        unsecured: 5432.1,
        unsecuredAPY: 14.6,
        credoraRating: "B / AA+",
    },
    {
        tokenSymbol: "DAI",
        netAPY: 11.3,
        totalDeposits: 7890.12,
        totalValueUSD: 4.98,
        curator: "Bitcoin",
        collateral: ["usdc", "algo", "add"],
        unsecured: 3289.62,
        unsecuredAPY: 7.5,
        credoraRating: "B / AA+",
    },
];

const sampleLoans: BorrowData[] = [
    {
        collateralToken: "USDC",
        loanToken: "DAI",
        liquidationLTV: 90,
        liquidationLTV2: 130,
        borrowAPY: 14.1,
        utilization: 16.8,
        totalDeposits: 3289.62,
        totalValueUSD: 1.96,
    },
    {
        collateralToken: "USDT",
        loanToken: "USDA",
        liquidationLTV: 85,
        liquidationLTV2: 130,
        borrowAPY: 12.3,
        utilization: 13.5,
        totalDeposits: 5432.1,
        totalValueUSD: 3.25,
    },
    {
        collateralToken: "USDA",
        loanToken: "USDA",
        liquidationLTV: 95,
        liquidationLTV2: 130,
        borrowAPY: 8.6,
        utilization: 17.5,
        totalDeposits: 7654.32,
        totalValueUSD: 1.55,
    },
    {
        collateralToken: "USDC",
        loanToken: "WETH",
        liquidationLTV: 92,
        liquidationLTV2: 130,
        borrowAPY: 4.9,
        utilization: 15.9,
        totalDeposits: 2987.65,
        totalValueUSD: 5.02,
    },
    {
        collateralToken: "USDT",
        loanToken: "WETH",
        liquidationLTV: 88,
        liquidationLTV2: 130,
        borrowAPY: 15.8,
        utilization: 18.5,
        totalDeposits: 4567.89,
        totalValueUSD: 2.89,
    },
    {
        collateralToken: "USDT",
        loanToken: "DAI",
        liquidationLTV: 93,
        liquidationLTV2: 130,
        borrowAPY: 14.7,
        utilization: 14.7,
        totalDeposits: 9876.54,
        totalValueUSD: 6.34,
    },
    {
        collateralToken: "USDA",
        loanToken: "USDA",
        liquidationLTV: 85,
        liquidationLTV2: 130,
        borrowAPY: 13.8,
        utilization: 15.9,
        totalDeposits: 1234.56,
        totalValueUSD: 0.75,
    },
    {
        collateralToken: "DAI",
        loanToken: "DAI",
        liquidationLTV: 92,
        liquidationLTV2: 130,
        borrowAPY: 12.7,
        utilization: 12.3,
        totalDeposits: 6789.01,
        totalValueUSD: 3.99,
    },
    {
        collateralToken: "WBTC",
        loanToken: "WETH",
        liquidationLTV: 90,
        liquidationLTV2: 130,
        borrowAPY: 15.3,
        utilization: 7.8,
        totalDeposits: 3210.98,
        totalValueUSD: 1.87,
    },
    {
        collateralToken: "WETH",
        loanToken: "WETH",
        liquidationLTV: 88,
        liquidationLTV2: 130,
        borrowAPY: 8.9,
        utilization: 4.6,
        totalDeposits: 8765.43,
        totalValueUSD: 5.67,
    },
];
